<div class="col-2">
    <div class="sectionBox">
        <div class="left-top-corner">
            <div class="right-top-corner"></div>
        </div>
        <div class="inner firstSection">
            <h3><span class="celeste">More</span> Tools</h3>
            <ul class="news">
                <li><a href="#">Internationalization - I18N.</a></li>
                <li><a href="#">Cleaned lifecycle.</a></li>
            </ul>
        </div>
    </div>

    <div class="sectionBox">
        <div class="inner">
            <h3><span class="celeste">Code</span> Generation</h3>
            <ul class="news">
                <li><a href="#">Propel ORM.</a></li>
                <li><a href="#">Scaffolding generation.</a></li>
            </ul>
        </div>
    </div>
    <div class="sectionBox">
        <div class="inner">
            <h3><span class="celeste">Latest</span> News</h3>
            <ul class="news">
                <li><a href="#">Chocala Framework 0.9 released!.</a></li>
                <li><a href="#">Next releases...</a></li>
            </ul>
        </div>
        <div class="right-bot-corner">
            <div class="left-bot-corner"></div>
        </div>
    </div>
</div>