<div id="header">
    <div class="fLeft">
        <h1>Chocala Framework
            <!--img src="<?=IMG_WEB;?>logo_chocala.png" alt="Chocala Framework" title="Chocala Framework" class="logo" /-->
        </h1>
    </div>
    <div class="fRight">
        <ul>
            <li><a href="#"><img src="<?=IMG_WEB;?>icon1-act.gif" alt="Home" title="Home"></a></li>
            <li><a href="#"><img src="<?=IMG_WEB;?>icon2-act.gif" alt="Contact" title="Contact"></a></li>
            <li><a href="#"><img src="<?=IMG_WEB;?>icon3-act.gif" alt="Sitemap" title="Sitemap"></a></li>
        </ul>
    </div>
    <div class="clear"></div>
    
    <div class="header-bar">    
    </div>
    
</div>