<?=CodeGenerator::TAG_OPEN_SHORT;?> BarView::renderBar('messages'); <?=CodeGenerator::TAG_CLOSE;?>

<div class="dialog" style="padding: 0 250px">
    <h1>#CLASS_NAME# Details</h1>

    <div class="fRight">
        <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> URI::toPage().'edit/'.#CLASS_INSTANCE#->getPrimaryKey(); <?=CodeGenerator::TAG_CLOSE;?>" class="linkGoBack">Edit #CLASS_NAME#</a>
        <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> URI::toPage().'delete/'.#CLASS_INSTANCE#->getPrimaryKey(); <?=CodeGenerator::TAG_CLOSE;?>" class="linkGoBack" onclick="return confirm('¿Do you sure to delete this record?');">Delete #CLASS_NAME#</a>
    </div>

    <hr />
    <?php
    foreach($mapedColumns as $columnMap):
        $camelName = SpecialStrings::camelCase($columnMap->getColumnName());
        $pascalName = SpecialStrings::pascalCase($columnMap->getColumnName());
        if($columnMap->isForeignKey()):
            $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
            $relatedFieldName = SpecialStrings::camelCase($hashColumns[$columnMap->getName()]['field']);
            $pascalRelatedClassName = SpecialStrings::pascalCase($relatedClassName);
            $relatedColumnName = SpecialStrings::camelCase($columnMap->getRelatedColumnName());
        ?>
    
    <div class="input">
        <label class="name"><?= $relatedClassName;?></label>
        <div class="value">
            <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> WEB_ROOT.'<?=$pascalRelatedClassName;?>/show/'.#CLASS_INSTANCE#->get<?= $relatedClassName;?>()->get<?=$relatedColumnName;?>(); <?=CodeGenerator::TAG_CLOSE;?>"><?=CodeGenerator::TAG_OPEN_SHORT;?> #CLASS_INSTANCE#->get<?= $relatedClassName;?>()->get<?= $relatedFieldName;?>(); <?=CodeGenerator::TAG_CLOSE;?></a>
        </div>
    </div>
        <?php
        elseif(!$columnMap->isPrimaryKey()):
        ?>
    
    <div class="input">
        <label class="name"><?= $camelName;?></label>
        <div class="value">
            <?=CodeGenerator::TAG_OPEN_SHORT;?> #CLASS_INSTANCE#->get<?= $camelName;?>(); <?=CodeGenerator::TAG_CLOSE;?>

        </div>
    </div>
        <?php
        endif;
    endforeach;
    ?>
    
</div>