<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width , initial-scale=1 ,maximum-scale=1" />
    <meta http-equiv="Content-language" content="es" />    
    <title><?=Configs::value('app.name');?> Autoresponder</title>
</head>
<body>
    <div style="font-size: 13px; margin: 5px; padding: 10px; text-align: center;">
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse; margin: 0 auto; text-align: left;">
            <tr><td style="color: #E36C0A; font-family: 'Calibri', Arial; font-size: 0.9em; font-style: italic; font-weight: bold;" width="100%">
                    <img src="<?=IMG_WEB;?>email/head.png" alt="<?=Configs::value('app.name');?>" title="<?=Configs::value('app.name');?>" border="0" />
                </td>
            </tr>
            <tr><td style="border-left: 1px solid #D3D3D3; border-right: 1px solid #D3D3D3; color: #222222; font-family: 'Calibri', Arial; padding: 5px 10px;">
                    <p>~NOMBRE~, Felicitaciones acabas de dar el Primer Paso para Registrarte Gratis al Directorio de Empresas <i style="color: #E36C0A; font-weight: bold; font-size: 1.2em;">ServiciosyCompras.com</i></p>
                    <p>Haz click en el link de color azul que encuentras mas abajo y te redireccionaremos a una página segura donde podrás completar tus datos de Empresa.</p>
                    <p><a href="~LINK_REG~" style="color: #1E5677;">~LINK_REG~</a></p>
                    <h4 style="color: #990000;">Importante</h4>
                    <p>
                        Debes Agregar el email <a href="mailto:<?=Configs::value('email.address.info');?>" style="color: #1E5677;"><?=Configs::value('email.address.info');?></a> en tu lista de Contactos
                        ya que Gmail, Hotmail, Yahoo, MSN u otros en servicios de email tienen muchos filtros y puede ser que envíen nuestros correos a Spam,
                        por eso debes de agregarlo en tus contactos para que el sistema no los filtre.
                    </p>
                    <p>Haz click en el siguiente enlace ahora para terminar con tu Registro.</p>
                    <p><a href="~LINK_REG~" style="color: #1E5677;">~LINK_REG~</a></p>
                    <br />
                    <p style="color: #1F497D;">
                        <u style="color: #E36C0A; text-decoration: underline; font-weight: bold; fonst-size: 1.2em;">ServiciosyCompras.com</u>
                    </p>
                    <br />
                    <p style="font-size: 0.8em; line-height: 1;">
                        Conforme a la Ley 34/2002 de Servicios de la Sociedad de la Información y Comercio Electrónico,
                        así como a la vigente Ley Orgánica 15/1999 de Protección de Datos de carácter personal,
                        su dirección de correo está incluida en nuestra base de datos con el fin de seguir ofreciéndole
                        información que consideramos de su interés. Tiene la opción de rectificar sus datos enviando un
                        correo a <?=Configs::value('email.address.info');?>.
                    </p>
                </td>
            </tr>
            <tr><td style="color: #E36C0A; font-family: 'Calibri', Arial; font-size: 0.9em; font-style: italic; font-weight: bold;">
                    <img src="<?=IMG_WEB;?>email/foot.png" alt="<?=Configs::value('app.name');?>" title="<?=Configs::value('app.name');?>" border="0" />
                </td>
            </tr>
        </table>
    </div>
</body>
</html>