<ul class="box-list">
    <li>
        <div class="box">
            <div class="right-corner">
                <div class="left-corner">
                    <div class="box1">
                        <div class="inner">
                            <h3><span class="softBlue">HMVC</span> Framework</h3>
                            <p>
                                A natural byproduct of striving for increased 
                                code modularity, re-usability, and maintaining a better separation 
                                of concerns.
                                <!--Chocala is a Model-View-Controller based Framework that provides 
                                a robust but lightweight structure for complex developments.-->
                                <a href="#"><img src="images/arrow.gif" alt="" /></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </li>
    <li class="alt">
        <div class="box">
            <div class="right-corner">
                <div class="left-corner">
                    <div class="box1">
                        <div class="inner">
                            <h3><span class="softBlue">Appbuilder</span> Generator</h3>
                            <p>
                                The engine generator builds applications including control, 
                                data sheet, metadata and template files.
                                <a href="#"><img src="images/arrow.gif" alt="" /></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </li>
    <li class="last">
        <div class="box">
            <div class="right-corner">
                <div class="left-corner">
                    <div class="box1">
                        <div class="inner">
                            <h3><span class="softBlue">Fast</span> Development</h3>
                            <p>
                                A simple environment that provides a robust structure with layers 
                                that optimize time and development resources
                                <a href="#"><img src="images/arrow.gif" alt="" /></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </li>
</ul>
<br />
<div class="indent">
    <div class="col-1">
        <h2><span class="softBlue">Speedly and Lightweight</span> Framework</h2>
        <p class="p0">
            Chocala is a PHP framework that help you develop complex Rich Internet Applications 
            quickly, with a best practices oriented approach, and saving a lot of time reusing code snippets. 
        </p>
        <p class="p0">
            Chocala having a high performance and super lightweight, there by reducing your server’s work.
            It has no dependencies on PECL extensions or PEAR libraries.
        </p>
        <img src="images/source-php.jpg" alt="" />
        <p>
            While Chocala is simple and lightweight, is a PHP framework for robust applications 
            giving developers the ability to create business applications with minimal effort.
        </p>
        <p class="p0">
            It is used for fast web programming when PHP 5 is used with a purely object-oriented source, 
            support for web service. It helps to re-conceptualize components, properties and events rather 
            than the parameters associated with URLs, procedures and minimizing queries. Some of its main 
            features are:
        </p>
        <ul>
            <li>
                Pluggable framework architecture that allows request lifecycles to be customized for each action.
            </li>
            <li>
                Hierarchical approach to internationalization that simplifies localizing applications.
            </li>
            <li>
                Supports automatic generation from data base table to classes, handling it on a model layer.
            </li>
            <li>
                Supports message translation, date and time formatting, number formatting, and interface localization.
            </li>
            <li>
                Input data can be accepted from a number of sources, currently supported are HTTP GET/POST, email, XML-RPC. SOAP support is anticipated in the near future.
            </li>
        </ul>
        <p class="p0">
            Chocala Framework can be configured, reused or extended easily. An optimal solution for developing 
            large-scale Web applications that also supports caching, jQuery-based AJAX, authentication and role-based 
            access control, scaffolding, input validation, widgets and theming.
        </p>

    </div>
    <div class="clear"></div>
</div>