<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file D:\host\chocalaFW\framework\generator\mapping\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'demog' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=demog;charset=UTF8',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'demog',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-conf.php');
return $conf;